spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/spendwise}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Kolkata

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET:spendwise-super-secret-key-that-is-at-least-256-bits-long-for-hs256}
    access-token-expiration: 900000      # 15 minutes
    refresh-token-expiration: 604800000  # 7 days

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
